version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 100
      runas: root

  ApplicationStart:
    - location: scripts/ApplicationStartHook.sh
      timeout: 100
      runas: root
